name: "adopt-ruff"

description: "Adopt ruff easily"
inputs:
  repository:
    description: "Repository name with owner. For example, ScDor/adopt-ruff"
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install adopt-ruff
      run: pip install git+https://github.com/ScDor/adopt-ruff
      shell: bash

    - name: Install ruff
      run: pip install ruff # TODO
      shell: bash

    - name: Parse ruff rules
      id: ruff_rules
      run: python -m ruff rule --all --output-format=json > rules.json
      shell: bash

    - name: Parse ruff violations
      id: ruff_output
      run: python -m  ruff . --output-format=json --select=ALL --exit-zero > violations.json
      shell: bash

    - name: Run adopt-ruff
      run: python -m adopt_ruff
      shell: bash

    - name: Set step summary
      run: cat result.md > $GITHUB_STEP_SUMMARY
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        path: artifacts
