name: "adopt-ruff"

description: "Adopt ruff easily"
inputs:
  repository:
    description: "Repository name with owner. For example, ScDor/adopt-ruff"
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Install adopt-ruff
      run: pip install git+https://github.com/ScDor/adopt-ruff -q
      shell: bash

    - name: Run adopt-ruff
      run: adopt-ruff
      shell: bash

    - name: Set step summary
      run: cat result.md > $GITHUB_STEP_SUMMARY
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        path: artifacts
