name: "adopt-ruff"

description: "Adopt ruff easily"
inputs:
  version:
    description: "version"
    default: master

runs:
  using: "composite"
  steps:
    - name: Install adopt-ruff
      run: pip install git+https://github.com/ScDor/adopt-ruff${{  inputs.version  }} -q
      shell: bash

    - name: Run adopt-ruff
      run: adopt-ruff
      shell: bash

    - name: Set step summary
      run: cat result.md > $GITHUB_STEP_SUMMARY
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        path: artifacts
