name: "adopt-ruff"

description: "Adopt ruff easily"
inputs:
  repository:
    description: "Repository name with owner. For example, ScDor/adopt-ruff"
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install adopt-ruff
      run: pip install git+https://github.com/ScDor/adopt-ruff@remove-poetry-install # TODO
      shell: bash

    - name: Install ruff
      run: pip install ruff # TODO
      shell: bash

    - name: Run adopt-ruff
      run: adopt_ruff
      shell: bash

    - name: Set step summary
      run: cat result.md > $GITHUB_STEP_SUMMARY
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        path: artifacts
