name: "adopt-ruff"

description: "Adopt ruff easily"
inputs:
  version:
    description: "adopt-ruff version to use"
    default: master
  repo-name:
    description: "name of the repository being checked"
    default: ${{  github.repository  }}
  include-sometimes-fixable:
    description: "whether to count sometimes-fixable rules as fixable"
    default: "False"
  include-preview:
    description: "whether to count preview rules"
    default: "True"

runs:
  using: "composite"
  steps:
    - name: Install adopt-ruff
      run: pip install git+https://github.com/ScDor/adopt-ruff@${{inputs.version}} -q
      shell: bash
    - name: set preview arg
      run: |
        print (${{ inputs.include-preview }})
      shell: python

    - name: Run adopt-ruff
      run: |
        adopt-ruff --repo-name=${{inputs.repo-name}} --sometimes-fixable=${{inputs.include-sometimes-fixable}}
      shell: bash

    - name: Set step summary
      run: cat result.md > $GITHUB_STEP_SUMMARY
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        path: artifacts
