name: "adopt-ruff"

description: "Adopt ruff easily"
inputs:
  version:
    description: "adopt-ruff version to use"
    default: master
  repo_name:
    description: "name of the repository being checked"
    default: ${{  github.repository  }}

runs:
  using: "composite"
  steps:
    - name: Install adopt-ruff
      run: pip install git+https://github.com/ScDor/adopt-ruff@${{inputs.version}} -q
      shell: bash

    - name: Run adopt-ruff
      run: adopt-ruff --repo-name=${{inputs.repo_name}}
      shell: bash

    - name: Set step summary
      run: cat result.md > $GITHUB_STEP_SUMMARY
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        path: artifacts
