name: Adopt Ruff
on: [push, workflow_dispatch]

jobs:
  adopt-ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: action.yml
