name: Adopt Ruff
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  adopt-ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install ruff
        run: pip install ruff
        shell: bash

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run the adopt-ruff action
        uses: ./
        with:
          ref: ${{  github.sha  }}
